---

name:
    wai-middleware-clacks
version:
    0.1.0.0
github:
    prikhi/wai-middleware-clacks
homepage:
    https://github.com/prikhi/wai-middleware-clacks#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2020 Pavan Rikhi
category:
    Web, Wai
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    GNU Terry Pratchett - Add the X-Clacks-Overhead Header to Wai Responses.

description: |
    /"You know they'll never really die while the Trunk is alive."/

    @wai-middleware-clacks@ is a middleware that inserts an arbitrary
    @X-Clacks-Overhead@ header into every Wai response. From
    <http://gnuterrypratchett.com GNU Terry Pratchett>:

    > In Terry Pratchett's Discworld series, the clacks are a series of
    > semaphore towers loosely based on the concept of the telegraph. Invented
    > by an artificer named Robert Dearheart, the towers could send messages
    > "at the speed of light" using standardized codes. Three of these codes
    > are of particular import:
    >
    > G: send the message on
    > N: do not log the message
    > U: turn the message around at the end of the line and send it back again
    >
    > When Dearheart's son John died due to an accident while working on a
    > clacks tower, Dearheart inserted John's name into the overhead of the
    > clacks with a "GNU" in front of it as a way to memorialize his son forever
    > (or for at least as long as the clacks are standing.)
    >
    >
    > Keeping the legacy of Sir Terry Pratchett alive forever. For as long as
    > his name is still passed along the Clacks, Death can't have him.

    Please see the
    <https://github.com/prikhi/wai-middleware-clacks/blob/master/README.md README>
    or
    <https://hackage.haskell.org/package/wai-middleware-clacks/docs/Network-Wai-Middleware-Clacks.html module documentation>
    for usage instructions.


ghc-options:
    - -Wall
when:
    condition:
        impl(ghc >= 8.0)
    then:
        ghc-options:
            - -Wcompat
            - -Wincomplete-record-updates
            - -Wincomplete-uni-patterns
            - -Wredundant-constraints
    else:
        ghc-options:
            - -fwarn-incomplete-record-updates
            - -fwarn-incomplete-uni-patterns


dependencies:
    - base >= 4.3 && < 5
    - base-compat-batteries


library:
    source-dirs:
        src
    dependencies:
        - bytestring < 1
        - case-insensitive < 2
        - http-types < 1
        - text < 2
        - wai < 4

tests:
    wai-middleware-clacks-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - wai-middleware-clacks
            - http-types
            - tasty
            - tasty-wai
            - wai
